name: Docker Build and Push to ACR and Update Container App

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Debug - List available registries
        run: |
          echo "Current subscription:"
          az account show --query "{subscriptionId:id, name:name}" -o table
          echo "Available container registries:"
          az acr list --query "[].{name:name, loginServer:loginServer, resourceGroup:resourceGroup}" -o table

      - name: Build and push Docker image
        run: |
          az acr build --registry ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }} --image python-ms:latest --platform linux/amd64 .
      
      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # - name: Update Azure Container App
      #   uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #       az containerapp update \
      #         --name ${{ secrets.CONTAINER_APP_NAME }} \
      #         --resource-group ${{ secrets.RESOURCE_GROUP }} \
      #         --image ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/python-ms:latest
